version: '3'

# volumes:
#   backend_local_postgres_data: {}
#   backend_local_postgres_data_backups: {}

services:
  backend:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: backend_local_django
    container_name: backend_local_django
    platform: linux/x86_64
    # depends_on:
    #   - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      # - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  # postgres:
  #   build:
  #     context: .
  #     dockerfile: ./compose/production/postgres/Dockerfile
  #   image: backend_production_postgres
  #   container_name: backend_local_postgres
  #   volumes:
  #     - backend_local_postgres_data:/var/lib/postgresql/data:Z
  #     - backend_local_postgres_data_backups:/backups:z
  #   env_file:
  #     - ./.envs/.local/.postgres
