# Generated by Django 4.0.3 on 2022-03-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinformation',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='page_information_docs_link', to='docs.docs'),
        ),
        migrations.AddField(
            model_name='pageinformation',
            name='subProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.subproducts'),
        ),
    ]
