# Generated by Django 4.0.3 on 2022-04-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageinformation',
            name='subProduct',
        ),
        migrations.AddField(
            model_name='subproducts',
            name='page_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.pageinformation'),
        ),
    ]
