# Generated by Django 4.0.3 on 2022-04-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_remove_pageinformation_page_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproducts',
            name='page_info',
        ),
        migrations.AddField(
            model_name='pageinformation',
            name='page_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.subproducts'),
        ),
    ]
