# Generated by Django 4.0.3 on 2022-04-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_remove_pageinformation_page_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='subProducts',
            new_name='sub_products',
        ),
    ]
