# Generated by Django 4.0.3 on 2022-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
