# Generated by Django 4.0.3 on 2022-03-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('HTML', models.TextField(blank=True, null=True)),
                ('CSS', models.TextField(blank=True, null=True)),
                ('validate_date', models.DateField(blank=True, null=True)),
                ('posted_date', models.DateField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.subproducts')),
            ],
        ),
    ]
